app = "senyo-hellofly"
name = "hellofly-deployment"

[build]
  image = "flyio/hellofly:latest"

[deploy]
  strategy = "rolling"

[[vm]]
  memory_mb = 1024
  cpus = 2
  cpu_kind = "shared"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = ["http", "tls"]
  port = 443

  [services.concurrency]
  type = "requests"
  soft_limit = 1024
  hard_limit = 1024

# [[mounts]]
#   source = "senyo-hellofly-vol"
#   destination = "/data"  

[[replicas]]
  region = "jnb"
  count = 2

[[replicas]]
  region = "ams"
  count = 3

[[replicas]]
  region = "iad"
  count = 1

